language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - poppler-utils

before_install:
  - mkdir -p ~/Rlib
  - echo 'crossref_email = name@example.com' > .Renviron

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: Q8AQQdRyHJC8fcyc5vD+H25QHfi6mkU8r7tKMxPLkA5RFkHQsOoO+9eUSH6g55rUw3EyIcj7SUbxmbjH4dhh3RNeLz+OmEcUzwKK1kza0VUWOgRwytHY66oigUFwewYwn+D+bNUYhcA/iXkBtlEx/oI+C9MSP2qR+Bd9AYfc5nw=
